# -*- mode: ruby -*-
# vi: set ft=ruby :

MASTER_IP = "192.168.56.10"
POD_CIDR = "10.244.0.0/16"
SERVICE_CIDR = "10.96.0.0/12"
NODE_COUNT = 2

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"
    config.vm.box_check_update = false

    # Kubernetes Master Node
    config.vm.define "k8s-master" do |master|
        master.vm.hostname = "k8s-master"
        master.vm.network "private_network", ip: MASTER_IP

        master.vm.provider "virtualbox" do |vb|
            vb.name = "k8s-master"
            vb.memory = 2048
            vb.cpus = 2
            vb.gui = false
        end

        master.vm.provision "shell", path: "scripts/common.sh"
        master.vm.provision "shell", path: "scripts/master.sh",
            env: {
                "MASTER_IP" => MASTER_IP,
                "POD_CIDR" => POD_CIDR,
                "SERVICE_CIDR" => SERVICE_CIDR
            }
    end

    # Kubernetes Worker Nodes
    (1..NODE_COUNT).each do |i|
        config.vm.define "k8s-worker#{i}" do |worker|
            worker.vm.hostname = "k8s-worker#{i}"
            worker.vm.network "private_network", ip: "192.168.56.#{i + 10}"

            worker.vm.provider "virtualbox" do |vb|
                vb.name = "k8s-worker#{i}"
                vb.memory = 2048
                vb.cpus = 2
                vb.gui = false
            end

            worker.vm.provision "shell", path: "scripts/common.sh"
            worker.vm.provision "shell", path: "scripts/worker.sh"
        end
    end
end